CREATE TABLE STUDENT 
( USN VARCHAR(10),
  NAME VARCHAR(10),
  PHONE INT,
  CGPA FLOAT,
  PRIMARY KEY(USN)
  );
/*
      OUTPUT : TABLE CREATED 
*/


DESC STUDENT ;
/* 
      O/P: 

NAME       NULL          TYPE
--------------------------------
USN        NOT NULL      VARCHAR2(10)
NAME                     VARCHAR2(10)
PHONE                    NUMBER(38)
CGPA                     FLOAT(126)

*/


SELECT * FROM STUDENT ;
/* 
-RUN THIS COMMAND TO SEE TABLE DETAILS 
-THE '*' IS USED TO SELECT ALL THE TUPLES 
-OUTPUT: NO ROW SELECTED
*/


INSERT INTO STUDENT VALUES('4SF23CI052','DHWANI',2214,8.5);
/*
- NOTE : INCLUDING " " INSTEAD OF '' WILL GIVE THE OUTPUT: COLUMN NOT ALLOWED
- PRIMARY KEY VALUES CANNOT BE DUPLICATE ( 2 STUDENTS CANNOT HAVE THE SAME USN)
- OTPUT : 1 ROW CREATED
*/


SELECT * FROM STUDENT ;
/*
USN          NAME      PHONE      CGPA
---------------------------------------
4SF23CI052   DHWANI    2214        8.5
*/


SET LINESIZE 1000 PAGESIZE 150;
/* THIS SQL COMMAND IS USED TO ADJUST THE OUTPUT'S ALLIGNMENT */


INSERT INTO STUDENT VALUES('&USN','&NAME','&PHONE','&CGPA');
/*
   - U CAN INSERT VALUE FOR USN , NAME , PH NO AND CGPA SEPARATELY I.E ONE AFTER THE OTHER FOR OTHER NEW ENTRIES
   - I FIND THIS WAY OF WRITING COMMAND IS MORE SYSTEMATIC THAN THE PREVIOUS ONE 
   - O/P : 1 ROW CREATED
*/


UPDATE STUDENT SET CGPA=9.0 WHERE USN='4SF23CI052' ;
/*
    THIS UPDATES THE CGPA FROM 8.5 (PREV VALUE) TO 9.0
*/


SELECT NAME,USN,CGPA
FROM STUDENT;
/* DISPLAYS THE TABLE DETAILS IN THE ORDER : NAME, USN AND THEN CGPA
*/
--------------------OR--------------------
SELECT USN,NAME,CGPA
FROM STUDENT;
/* DISPLAYS THE TABLE DETAILS IN THE ORDER :  USN, NAME AND THEN CGPA
*/


SELECT USN, CGPA FROM STUDENT WHERE NAME='DHWANI' ;
/* DISPLAYS USN AND CGPA OF ALL THE DHWANIs IN THE TABLE */

DELETE FROM STUDENT WHERE USN='4SF23CI000' ;
/*
  DELETES THE TUPLE OF STUDENT WITH USN 0  
*/

COMMIT ;
/* THIS COMMAND IS VERY ESSENTIAL . IT MUST BE USED IN ORDER TO SAVE WHAT EVER WE'VE DONE TILL NOW :) */

